markdown: kramdown
highlighter: rouge

exclude: ['Gemfile*', 'bower_components/', 'node_modules/', '*.scss', 'gulpfile.js', 'serve.sh', '*.codekit', 'README*']

permalink: writing/:title
timezone: Europe/Sofia

title: Angel Paunchev
url: http://paunchev.net
