# Site settings
title: Angel Paunchev
email: apaunchev@gmail.com
description: ""
baseurl: ""
url: "http://paunchev.net"
google-analytics-id: "UA-10660049-1"
gravatar: e17e058f8ca028c6e00b9434715fa74a

# Build settings
markdown: kramdown
permalink: writing/:title
timezone: Europe/Sofia
exclude: ["config.codekit", "README.md", "Gemfile*", "*.scss", "bower_components/"]
gems:
  - jekyll-sitemap

# Glynn settings
ftp_host: "paunchev.net"
ftp_dir: "/public_html/"
ftp_passive: false
