---
markdown: kramdown
highlighter: rouge
exclude: 
  - "Gemfile*"
  - "bower_components/"
  - "node_modules/"
  - "*.scss"
  - "gulpfile.js"
  - "serve.sh"
  - "*.codekit"
  - "README*"
title: paunchev.net
name: Angel Paunchev
description: Angel Paunchev is a software developer from Bulgaria.
url: http://paunchev.net
permalink: :title
timezone: Europe/Sofia
logo: /images/me.jpg
author:
  twitter: apaunchev
