# Site settings
title: Angel Paunchev
email: apaunchev@gmail.com
description: ""
baseurl: ""
url: "http://paunchev.net"
google-analytics-id: "UA-10660049-1"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
timezone: Europe/Sofia
exclude: ["config.codekit", "README.md"]
gems:
  - jekyll-sitemap

# Glynn settings
ftp_host: "paunchev.net"
ftp_dir: "/public_html/"
ftp_passive: false
