markdown: kramdown
highlighter: rouge

exclude: ['Gemfile*', 'bower_components/', 'node_modules/', '*.scss', 'gulpfile.js', 'serve.sh', '*.codekit', 'README*']

name: Angel Paunchev
description: Angel Paunchev is a web developer from Bulgaria.

url: http://paunchev.net
permalink: :title
timezone: Europe/Sofia
locale: en-GB

logo: /images/me.jpg

author:
    twitter: apaunchev
